[2023-08-06T16:18:24.168+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow.Get-BTC-Price scheduled__2023-08-05T00:00:00+00:00 [queued]>
[2023-08-06T16:18:24.178+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow.Get-BTC-Price scheduled__2023-08-05T00:00:00+00:00 [queued]>
[2023-08-06T16:18:24.179+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-06T16:18:24.188+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): Get-BTC-Price> on 2023-08-05 00:00:00+00:00
[2023-08-06T16:18:24.194+0000] {standard_task_runner.py:57} INFO - Started process 1589 to run task
[2023-08-06T16:18:24.198+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow', 'Get-BTC-Price', 'scheduled__2023-08-05T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/demo.py', '--cfg-path', '/tmp/tmp88mk6720']
[2023-08-06T16:18:24.200+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask Get-BTC-Price
[2023-08-06T16:18:24.256+0000] {task_command.py:410} INFO - Running <TaskInstance: Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow.Get-BTC-Price scheduled__2023-08-05T00:00:00+00:00 [running]> on host 0209446e4861
[2023-08-06T16:18:24.336+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow' AIRFLOW_CTX_TASK_ID='Get-BTC-Price' AIRFLOW_CTX_EXECUTION_DATE='2023-08-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-05T00:00:00+00:00'
[2023-08-06T16:18:24.685+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/demo.py", line 49, in get_data_btc
    output = [date.today(), data['last'], data['buy'], data['sell'], data['high'], data['low']]
KeyError: 'last'
[2023-08-06T16:18:24.702+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Korelasi-Harga-Emas-Bitcoin-IHSG-Workflow, task_id=Get-BTC-Price, execution_date=20230805T000000, start_date=20230806T161824, end_date=20230806T161824
[2023-08-06T16:18:24.713+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 30 for task Get-BTC-Price ('last'; 1589)
[2023-08-06T16:18:24.749+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-06T16:18:24.765+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
